### ISSUE TITLE
Getting connection error - may be openai api key is not set property - need help

### ISSUE THREAD

**Issue by suraj007118** [lucgagan/auto-playwright#21]
Hello,
I have set my api key within options variable as below:

import { test, expect } from '@playwright/test'
import { auto } from 'auto-playwright'

test.describe('todo tests', () => {

 const options = {
    openaiApiKey: '12eretretrtydsfgfdgxcxdv',
  }

  test('sample AI test @auto', async ({ page }) => {
    const email = '*********'
    const password = '**********'
    await page.goto('https://************')
    await page.waitForTimeout(3000)

    await auto('Verify that **** Logo is displayed', { page, test }, options)
    await auto('Click on "Sign In" button', { page, test }, options)
    await page.waitForTimeout(5000)
    await auto('Verify that a pop up modal is displayed', { page, test }, options)
    await auto('Click on link "**********"', { page, test })
    await auto('Verify a login screen is displayed', { page, test }, options)

but I get error:

    Error: Connection error.

        at OpenAI.makeRequest (/Users/suraj.kelkar/Downloads/playwright-typeScript/node_modules/.pnpm/openai@4.24.1/node_modules/openai/src/core.ts:400:13)
        at ChatCompletionRunner._createChatCompletion (/Users/suraj.kelkar/Downloads/playwright-typeScript/node_modules/.pnpm/openai@4.24.1/node_modules/openai/src/lib/AbstractChatCompletionRunner.ts:432:28)
        at ChatCompletionRunner._runFunctions (/Users/suraj.kelkar/Downloads/playwright-typeScript/node_modules/.pnpm/openai@4.24.1/node_modules/openai/src/lib/AbstractChatCompletionRunner.ts:481:46)

**Comment by jerome-basa** [comment]
Hello @suraj007118, I am having the same issue. Have you fixed yours?
