### ISSUE TITLE
punycode and 

### ISSUE THREAD

**Issue by rebajz** [lucgagan/auto-playwright#45]
I have installed nodejs v22.9.0 and try "auto-playwright": "1.16.0",

when i add auto-playwright into my project, and copy your demo code for test and try run this test, i got everytime this messege:

(node:365986) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
  

    TypeError: Cannot read properties of undefined (reading 'defaults')

        at sanitizeHtml (/app/node_modules/auto-playwright/dist/sanitizeHtml.js:23:46)
        at getSnapshot (/app/node_modules/auto-playwright/dist/getSnapshot.js:7:46)
        at runTask (/app/node_modules/auto-playwright/dist/auto.js:37:19)
        at /app/node_modules/auto-playwright/dist/auto.js:17:24

**Comment by jaykhatri171** [comment]
It's resolved for me, Just replace the sanitizeHTML.js with this

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.sanitizeHtml = void 0;
const sanitize = require("sanitize-html");
/**
 * The reason for sanitization is because OpenAI does not need all of the HTML tags
 * to know how to interpret the website, e.g. it will not make a difference to AI if
 * we include or exclude <script> tags as they do not impact the already rendered DOM.
 *
 * In my experience, reducing HTML only to basic tags produces faster and more reliable prompts.
 *
 * Note that the output of this function is designed to interpret only the HTML tags.
 * For instructions that rely on visual cues (e.g. "click red button") we intend to
 * combine HTML with screenshots in the future versions of this library.
 */
const sanitizeHtml = (subject) => {
    return sanitize(subject, {
        // The default allowedTags list already includes _a lot_ of commonly used tags.
        // https://www.npmjs.com/package/sanitize-html#default-options
        //
        // I don't see a need for this to be configurable at the moment,
        // as it already covers all the layout tags, but we can revisit this if necessary.
        allowedTags: sanitize.defaults.allowedTags.concat([
            "button",
            "form",
            "img",
            "input",
            "select",
            "textarea",
        ]),
        // Setting allowedAttributes to false will allow all attributes.
        allowedAttributes: false,
    });
};
exports.sanitizeHtml = sanitizeHtml;
```

**Comment by GRmeB** [comment]
The problem in this case is that there is no new release built that includes the fixed code in main branch. so, the latest release doesn't contain the current clean main branch status.
