### ISSUE TITLE
issue with type definitions for sanitize-html

### ISSUE THREAD

**Issue by vijaykramesh** [lucgagan/auto-playwright#7]
It seems like I'm getting invalid javascript generated from sanitizeHtml.ts 

this code

```typescript
export const sanitizeHtml = (subject: string) => {
  return sanitize(subject, {
    // The default allowedTags list already includes _a lot_ of commonly used tags.
    // https://www.npmjs.com/package/sanitize-html#default-options
    //
    // I don't see a need for this to be configurable at the moment,
    // as it already covers all the layout tags, but we can revisit this if necessary.
    allowedTags: sanitize.defaults.allowedTags.concat([
      "button",
      "form",
      "img",
      "input",
      "select",
      "textarea",
    ]),
    // Setting allowedAttributes to false will allow all attributes.
    allowedAttributes: false,
  });
};
```

turns into 

```javascript
const sanitizeHtml = (subject) => {
    return (0, sanitize_html_1.default)(subject, {

        // The default allowedTags list already includes _a lot_ of commonly used tags.
        // https://www.npmjs.com/package/sanitize-html#default-options
        //
        // I don't see a need for this to be configurable at the moment,
        // as it already covers all the layout tags, but we can revisit this if necessary.
        allowedTags: sanitize_html_1.default.defaults.allowedTags.concat([
            "button",
            "form",
            "img",
            "input",
            "select",
            "textarea",
        ]),
        // Setting allowedAttributes to false will allow all attributes.
        allowedAttributes: false,
    });
};
```

which fails with 

```
 TypeError: Cannot read properties of undefined (reading 'defaults')
    at sanitizeHtml (/Users/vijay/work/prj/workspace/node_modules/.pnpm/auto-playwright@1.8.1_@playwright+test@1.34.3/node_modules/auto-playwright/dist/sanitizeHtml.js:25:46)
    at getSnapshot (/Users/vijay/work/prj/workspace/node_modules/.pnpm/auto-playwright@1.8.1_@playwright+test@1.34.3/node_modules/auto-playwright/dist/getSnapshot.js:7:46)
```

If i manually adjust the javascript file in dist to be like

```javascript
const sanitizeHtml = (subject) => {
    return (0, sanitize_html_1)(subject, {

        // The default allowedTags list already includes _a lot_ of commonly used tags.
        // https://www.npmjs.com/package/sanitize-html#default-options
        //
        // I don't see a need for this to be configurable at the moment,
        // as it already covers all the layout tags, but we can revisit this if necessary.
        allowedTags: sanitize_html_1.defaults.allowedTags.concat([
            "button",
            "form",
            "img",
            "input",
            "select",
            "textarea",
        ]),
        // Setting allowedAttributes to false will allow all attributes.
        allowedAttributes: false,
    });
};
```

it all seems to work...  looking at the underlying type in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sanitize-html/index.d.ts it seems correct to me...

**Comment by lucgagan** [comment]
Do you have `skipLibCheck` set to `true`?

**Comment by vijaykramesh** [comment]
where would I set that? I don't see that string anywhere in the repo...

**Comment by vijaykramesh** [comment]
ahh yep I do

**Comment by lucgagan** [comment]
It is pretty unusual to have that enabled in your project.

I will leave this open as I am unsure as to what is the underlying issue, but it is not an issue that I will prioritize. I suspect it is some odd mismatch between package and your project `tsconfig.json`.

**Comment by derenandrii** [comment]
@lucgagan facing the same issue

**Comment by ostapel** [comment]
I have the same issue :)

**Comment by tntexplosivesltd** [comment]
Having this issue as well, using the default project created by calling `npm init playwright`.

Might be worth looking into if this is the 'default' out of box experience when using Playwright
I wonder if it's an issue with your tsconfig @lucgagan, as it appears that the JS coming from your .ts files is invalid outside your project.
